// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 dropped `directUrl`; the config datasource only supports
    // `url` (+ `shadowDatabaseUrl`). The CLI (migrate/db push/studio) uses
    // this, so it must be a SESSION connection (Supabase port 5432) — the
    // transaction pooler (6543) can't grant the advisory lock migrations need.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
